(()=>{
function injectAnalyticsUI(){
  const wrap=document.querySelector('.wrap'); if(!wrap||document.getElementById('analytics')) return;
  const sec=document.createElement('section'); sec.id='analytics'; sec.className='page';
  sec.innerHTML=`
    <div class="card"><div class="title"><h2>Riepilogo annuale</h2><select id="annualYear" style="max-width:105px" onchange="renderAnalytics()"></select></div>
      <div class="annualGrid">
        <div class="miniStat"><span>Entrate</span><b id="annualIncome">€0</b></div>
        <div class="miniStat"><span>Uscite</span><b id="annualOut">€0</b></div>
        <div class="miniStat"><span>Risparmio</span><b id="annualSave">€0</b></div>
        <div class="miniStat"><span>Media spese/mese</span><b id="annualAvg">€0</b></div>
      </div>
      <div class="hint" id="annualHint"></div>
    </div>
    <div class="card"><div class="title"><h2>Confronto mese precedente</h2><span class="muted" id="compareLabel"></span></div><div id="monthCompare"></div></div>
    <div class="card"><div class="title"><h2>Media storica per categoria</h2><span class="muted">mesi con dati</span></div><div id="categoryAverage"></div></div>
    <div class="card"><div class="title"><h2>Andamento risparmio</h2></div><div class="chartWrap"><canvas id="savingChart"></canvas></div></div>`;
  wrap.appendChild(sec);
  const nav=document.querySelector('.tabs>div');
  if(nav){nav.style.gridTemplateColumns='repeat(6,minmax(0,1fr))';const b=document.createElement('button');b.dataset.tab='analytics';b.innerHTML='<b>▥</b>Analisi';b.onclick=()=>{tab('analytics',b);requestAnimationFrame(()=>drawSavingChart())};nav.insertBefore(b,nav.lastElementChild);}
  const settings=document.getElementById('settings');
  if(settings){const backup=document.createElement('div');backup.className='card';backup.innerHTML=`<div class="title"><h2>Backup dati</h2><span class="muted">solo sul dispositivo</span></div><div class="hint">Esporta periodicamente un backup. Puoi poi reimportarlo su questo o su un altro dispositivo.</div><div class="backupActions"><button onclick="exportBackup()">Esporta backup</button><label class="importBtn">Importa backup<input id="backupFile" type="file" accept="application/json" onchange="importBackup(this.files[0])"></label></div>`;settings.appendChild(backup);}
  const st=document.createElement('style');st.textContent=`.annualGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-bottom:10px}.miniStat{background:#f8fafc;border:1px solid #eef1f4;border-radius:13px;padding:11px}.miniStat span{display:block;font-size:11px;color:#64748b;font-weight:700}.miniStat b{font-size:18px;margin-top:3px;display:block}.compareGrid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px}.compareBox{background:#f8fafc;border-radius:12px;padding:10px}.compareBox span{font-size:10px;color:#64748b;display:block}.compareBox b{display:block;margin-top:3px}.backupActions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.importBtn{display:flex;justify-content:center;align-items:center;background:#eef2f6;color:#0f172a;border-radius:12px;font-weight:800;font-size:13px;cursor:pointer}.importBtn input{display:none}@media(min-width:650px){.annualGrid{grid-template-columns:repeat(4,1fr)}}`;document.head.appendChild(st);
}
function yearsAvailable(){let y=new Set(Object.keys(d.incomeHistory||{}).map(m=>m.slice(0,4)));(d.expenses||[]).forEach(x=>y.add((x.month||'').slice(0,4)));y.add(String(new Date().getFullYear()));return [...y].filter(Boolean).sort()}
function monthsForYear(y){return historyMonths().filter(m=>m.startsWith(y+'-'))}
function averageCategoryAll(){let ms=historyMonths().filter(m=>monthTotal(m)>0), cats={};ms.forEach(m=>{let t=categoryTotals(m);Object.entries(t).forEach(([k,v])=>cats[k]=(cats[k]||0)+v)});return Object.entries(cats).map(([k,v])=>[k,ms.length?v/ms.length:0]).sort((a,b)=>b[1]-a[1])}
function prevMonth(m){let [y,mo]=m.split('-').map(Number);let dt=new Date(y,mo-2,1);return dt.toISOString().slice(0,7)}
window.renderAnalytics=function(){
  if(!document.getElementById('analytics')) return; let years=yearsAvailable(),sel=document.getElementById('annualYear');let keep=sel.value||String(new Date().getFullYear());sel.innerHTML=years.map(y=>`<option ${y===keep?'selected':''}>${y}</option>`).join('');let y=sel.value||years.at(-1),ms=monthsForYear(y),inc=ms.reduce((s,m)=>s+incomeFor(m),0),out=ms.reduce((s,m)=>s+monthTotal(m),0),save=inc-out,monthsWithData=Math.max(1,ms.filter(m=>incomeFor(m)||monthTotal(m)).length);annualIncome.textContent=eur(inc);annualOut.textContent=eur(out);annualSave.textContent=eur(save);annualAvg.textContent=eur(out/monthsWithData);let rate=inc?save/inc:0;annualHint.innerHTML=`Nel ${y} hai risparmiato <b class="${save>=0?'good':'bad'}">${eur(save)}</b>, pari al <b>${(rate*100).toFixed(1)}%</b> delle entrate registrate.`;
  let cur=selectedHistory||monthNow(),prev=prevMonth(cur),co=monthTotal(cur),po=monthTotal(prev),ci=incomeFor(cur),pi=incomeFor(prev),cs=ci-co,ps=pi-po;compareLabel.textContent=`${fmtMonth(cur)} vs ${fmtMonth(prev)}`;let diff=co-po,sDiff=cs-ps;monthCompare.innerHTML=`<div class="compareGrid"><div class="compareBox"><span>Spese</span><b>${eur(co)}</b><small class="${diff<=0?'good':'bad'}">${diff===0?'=':(diff>0?'+':'')+eur(diff)}</small></div><div class="compareBox"><span>Risparmio</span><b>${eur(cs)}</b><small class="${sDiff>=0?'good':'bad'}">${sDiff===0?'=':(sDiff>0?'+':'')+eur(sDiff)}</small></div><div class="compareBox"><span>Entrate</span><b>${eur(ci)}</b><small>${pi?(((ci-pi)/pi)*100).toFixed(0)+'%':'—'}</small></div></div>`;
  categoryAverage.innerHTML=averageCategoryAll().map(([k,v])=>`<div class="row"><div class="name">${esc(k)}</div><div class="money">${eur(v)}/m</div></div>`).join('')||'<div class="empty">Nessun dato storico.</div>';if(document.getElementById('analytics').classList.contains('on'))requestAnimationFrame(()=>drawSavingChart());
}
function drawSavingChart(){let cv=document.getElementById('savingChart');if(!cv)return;let rect=cv.getBoundingClientRect();if(rect.width<20||rect.height<20)return;let ctx=cv.getContext('2d'),r=devicePixelRatio||1;cv.width=Math.round(rect.width*r);cv.height=Math.round(rect.height*r);ctx.setTransform(r,0,0,r,0,0);let w=rect.width,h=rect.height,p=28,ms=historyMonths().slice(-12),vals=ms.map(m=>incomeFor(m)-monthTotal(m)),mx=Math.max(1,...vals.map(Math.abs));ctx.clearRect(0,0,w,h);ctx.strokeStyle='#e5e7eb';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p,h/2);ctx.lineTo(w-8,h/2);ctx.stroke();ctx.lineWidth=3;ctx.strokeStyle='#0f172a';ctx.beginPath();vals.forEach((v,i)=>{let x=p+(w-p-16)*(ms.length===1?.5:i/(ms.length-1)),y=h/2-(v/mx)*(h/2-p);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#0f172a';vals.forEach((v,i)=>{let x=p+(w-p-16)*(ms.length===1?.5:i/(ms.length-1)),y=h/2-(v/mx)*(h/2-p);ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()});ctx.fillStyle='#64748b';ctx.font='10px system-ui';let every=Math.max(1,Math.ceil(ms.length/6));ms.forEach((m,i)=>{if(i%every===0||i===ms.length-1){let x=p+(w-p-16)*(ms.length===1?.5:i/(ms.length-1));ctx.fillText(m.slice(5),x-6,h-6)}})}
window.exportBackup=function(){let payload={version:1,exportedAt:new Date().toISOString(),data:d};let blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`budget-helper-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
window.importBackup=function(file){if(!file)return;let r=new FileReader();r.onload=()=>{try{let p=JSON.parse(r.result);if(!p.data)throw Error();if(!confirm('Sostituire i dati attuali con questo backup?'))return;localStorage.setItem(KEY,JSON.stringify(p.data));location.reload()}catch(e){alert('Backup non valido.')}};r.readAsText(file)}
injectAnalyticsUI(); const _render=render; render=function(){_render();renderAnalytics()};renderAnalytics();
})();