(()=>{
const localToday=()=>{let n=new Date(),p=x=>String(x).padStart(2,'0');return `${n.getFullYear()}-${p(n.getMonth()+1)}-${p(n.getDate())}`};
function initAssistantSchema(){d.goalContributions=d.goalContributions||[];d.deadlines.forEach(x=>x.cat=x.cat||guessDeadlineCat(x.name));localStorage.setItem(KEY,JSON.stringify(d))}
function guessDeadlineCat(n){n=(n||'').toLowerCase();if(n.includes('auto')||n.includes('macchina'))return'Finanziamenti';if(n.includes('assicur')||n.includes('bollo'))return'Assicurazione/Bollo';if(n.includes('bollett')||n.includes('uten'))return'Utenze';return'Altro'}
function monthContrib(m){return (d.goalContributions||[]).filter(x=>x.month===m).reduce((s,x)=>s+Number(x.amount||0),0)}
function daysLeft(){let n=new Date(),last=new Date(n.getFullYear(),n.getMonth()+1,0).getDate();return Math.max(1,last-n.getDate()+1)}
function smartBudgets(){let used=categoryTotals(monthNow()),base=d.cats.map(([name,p])=>({name,base:d.life*p/100,used:used[name]||0}));let overs=base.reduce((s,x)=>s+Math.max(0,x.used-x.base),0),donors=base.filter(x=>x.used<x.base),room=donors.reduce((s,x)=>s+(x.base-x.used),0);return base.map(x=>{let adjusted=x.base;if(x.used<x.base&&overs>0&&room>0)adjusted=Math.max(x.used,x.base-overs*((x.base-x.used)/room));return{...x,adjusted,left:adjusted-x.used}})}
function assistantText(){let c=currentCalc(),sb=smartBudgets(),overs=sb.filter(x=>x.used>x.base),real=monthContrib(c.m),left=Math.max(0,d.life-c.spent),daily=left/daysLeft();let parts=[];if(overs.length){let total=overs.reduce((s,x)=>s+x.used-x.base,0),cuts=sb.filter(x=>x.adjusted<x.base-.01).map(x=>`${x.name} ${eur(x.adjusted)}`).join(', ');parts.push(`Hai superato ${overs.length===1?'una categoria':'alcune categorie'} di <b>${eur(total)}</b>. Per restare nel piano ho ricalcolato i budget residui${cuts?`: ${cuts}`:''}.`)}else parts.push(`Sei <b class="good">in linea</b> con i budget discrezionali.`);parts.push(`Hai <b>${eur(left)}</b> disponibili per ${daysLeft()} giorni, circa <b>${eur(daily)}/giorno</b>.`);parts.push(real?`Questo mese hai accantonato realmente <b>${eur(real)}</b> negli obiettivi.`:`Non hai ancora confermato risparmio reale negli obiettivi questo mese.`);return parts.join(' ')}
function injectHomeAssistant(){let home=document.getElementById('home');if(!home||document.getElementById('assistantCard'))return;let card=document.createElement('div');card.id='assistantCard';card.className='card assistantCard';card.innerHTML='<div class="title"><h2>Assistente del mese</h2><span class="pill good">LIVE</span></div><div id="assistantCopy" class="hint"></div><div class="assistantStats"><div><span>Risparmio reale</span><b id="realSaving">€0</b></div><div><span>Budget giornaliero</span><b id="dailyBudget">€0</b></div></div>';let hero=home.querySelector('.hero');hero.insertAdjacentElement('afterend',card)}
function renderAssistant(){if(!document.getElementById('assistantCard'))return;let c=currentCalc(),real=monthContrib(c.m),left=Math.max(0,d.life-c.spent);assistantCopy.innerHTML=assistantText();realSaving.textContent=eur(real);dailyBudget.textContent=eur(left/daysLeft());let sb=smartBudgets();budgetRows.innerHTML=sb.map(x=>{let pc=x.adjusted?Math.min(100,x.used/x.adjusted*100):0;return `<div class="row"><div class="grow"><div class="name">${esc(x.name)}</div><div class="meta">${eur(x.used)} spesi · budget aggiornato ${eur(x.adjusted)}${Math.abs(x.adjusted-x.base)>.01?` <span class="pill warn">riallocato da ${eur(x.base)}</span>`:''}</div><div class="bar"><i class="${x.used>x.adjusted?'badbar':x.used>x.adjusted*.8?'warnbar':''}" style="width:${pc}%"></i></div></div><div class="money ${x.left<0?'bad':''}">${eur(x.left)}</div></div>`}).join('')}
function patchGoals(){window.addSaving=function(i){let g=d.goals[i],a=Number(prompt(`Quanto hai realmente accantonato per ${g.name} questo mese?`)||0);if(a>0){let actual=Math.min(a,Math.max(0,g.target-g.saved));g.saved=Math.min(g.target,g.saved+actual);d.goalContributions.push({id:uid(),goal:g.name,amount:actual,month:monthNow(),date:localToday()});persist()}}}
function patchDeadlinePayment(){window.payDeadline=function(id){let x=d.deadlines.find(v=>v.id===id);if(!x)return;let current=x.next,next=addMonths(x.next,FREQ[x.freq]||1),ok=confirm(`Confermi di aver pagato “${x.name}” per ${eur(x.amount)}?\n\nVerrà registrata anche come spesa in “${x.cat||guessDeadlineCat(x.name)}”.\nProssima scadenza: ${new Date(next+'T12:00:00').toLocaleDateString('it-IT')}`);if(!ok)return;d.expenses.push({id:uid(),amount:Number(x.amount),cat:x.cat||guessDeadlineCat(x.name),desc:x.name,date:localToday(),month:monthNow(),source:'deadline',deadlineId:x.id});x.next=next;persist()}}
function quickCategories(){let sheet=document.querySelector('.sheet');if(!sheet||document.getElementById('quickCats'))return;let qc=document.createElement('div');qc.id='quickCats';qc.className='quickCats';let select=document.getElementById('exCat');select.insertAdjacentElement('beforebegin',qc);renderQuickCats()}
function renderQuickCats(){let q=document.getElementById('quickCats');if(!q)return;let names=[...d.cats.map(x=>x[0]),...Object.keys(d.essentialBudgets)].slice(0,5);q.innerHTML=names.map((n,i)=>`<button type="button" class="${i===0?'on':''}" onclick="pickQuickCat('${String(n).replaceAll("'","\\'")}',this)">${esc(n)}</button>`).join('');if(names[0])exCat.value=names[0]}
window.pickQuickCat=function(n,b){exCat.value=n;document.querySelectorAll('#quickCats button').forEach(x=>x.classList.remove('on'));b.classList.add('on')};
function patchExpense(){window.addExpense=function(){let a=Number(exAmt.value);if(!(a>0))return;let date=localToday();d.expenses.push({id:uid(),amount:a,cat:exCat.value,desc:exDesc.value.trim(),date,month:date.slice(0,7)});exAmt.value='';exDesc.value='';closeExpense();persist()}}
function patchDeadlineForm(){let form=document.querySelector('#deadlines .form3');if(!form||document.getElementById('dlCat'))return;let sel=document.createElement('select');sel.id='dlCat';let names=[...Object.keys(d.essentialBudgets),...d.cats.map(x=>x[0]),'Utenze','Assicurazione/Bollo','Finanziamenti','Imposte','Altro'];sel.innerHTML=[...new Set(names)].map(x=>`<option>${esc(x)}</option>`).join('');form.appendChild(sel);let old=window.addDeadline;window.addDeadline=function(){if(!dlName.value.trim()||!(Number(dlAmount.value)>0)||!dlDate.value)return;d.deadlines.push({id:uid(),name:dlName.value.trim(),amount:Number(dlAmount.value),freq:dlFreq.value,next:dlDate.value,cat:dlCat.value});dlName.value=dlAmount.value=dlDate.value='';persist()}}
const style=document.createElement('style');style.textContent=`.assistantCard{border:1px solid #dfe7f3}.assistantStats{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:10px}.assistantStats>div{background:#f6f8fb;border-radius:15px;padding:12px}.assistantStats span{display:block;color:#7b879b;font-size:11px;font-weight:750}.assistantStats b{display:block;margin-top:3px;font-size:18px}.quickCats{display:flex;gap:7px;overflow-x:auto;padding:1px 0 3px;scrollbar-width:none}.quickCats::-webkit-scrollbar{display:none}.quickCats button{white-space:nowrap;background:#f1f4f8;color:#475569;min-height:38px;padding:8px 11px;font-size:11px}.quickCats button.on{background:#0d1b35;color:#fff}`;document.head.appendChild(style);
initAssistantSchema();injectHomeAssistant();quickCategories();patchGoals();patchDeadlinePayment();patchExpense();patchDeadlineForm();const prevRender=render;render=function(){prevRender();renderAssistant();renderQuickCats()};render();
})();