(()=>{
function injectDeadlineEditor(){if(document.getElementById('deadlineEditBack'))return;let back=document.createElement('div');back.id='deadlineEditBack';back.className='sheetBack';back.innerHTML=`<div class="sheet"><div class="title"><div><span class="muted">MODIFICA SCADENZA</span><h2 id="deTitle">Scadenza</h2></div></div><div class="form"><label class="fieldLabel">Prossima data<input id="deDate" type="date"></label><div class="sheetActions"><button class="ghost" type="button" onclick="closeDeadlineEdit()">Annulla</button><button type="button" onclick="saveDeadlineDate()">Salva data</button></div></div></div>`;back.addEventListener('click',e=>{if(e.target===back)closeDeadlineEdit()});document.body.appendChild(back)}
let editingDeadlineId=null;
window.openDeadlineEdit=function(id){let x=d.deadlines.find(v=>v.id===id);if(!x)return;injectDeadlineEditor();editingDeadlineId=id;deTitle.textContent=x.name;deDate.value=x.next||'';deadlineEditBack.classList.add('on')}
window.closeDeadlineEdit=function(){let el=document.getElementById('deadlineEditBack');if(el)el.classList.remove('on');editingDeadlineId=null}
window.saveDeadlineDate=function(){if(!editingDeadlineId)return;let x=d.deadlines.find(v=>v.id===editingDeadlineId);if(!x)return;let next=deDate.value;if(!next)return alert('Seleziona una data valida.');let old=x.next;if(old===next){closeDeadlineEdit();return}let ok=confirm(`Confermi la nuova data per “${x.name}”?\n\nDa: ${old?new Date(old+'T12:00:00').toLocaleDateString('it-IT'):'—'}\nA: ${new Date(next+'T12:00:00').toLocaleDateString('it-IT')}`);if(!ok)return;x.next=next;closeDeadlineEdit();persist()}
function enhanceDeadlineRows(){document.querySelectorAll('#deadlineList .row').forEach(row=>{let actions=row.querySelector('.deadlineActions');if(!actions||actions.querySelector('.editDeadlineDateBtn'))return;let pay=actions.querySelector('button[onclick^="payDeadline"]'),del=actions.querySelector('button[onclick^="deleteDeadline"]');let source=(pay?.getAttribute('onclick')||del?.getAttribute('onclick')||''),m=source.match(/\('([^']+)'\)/);if(!m)return;let id=m[1],b=document.createElement('button');b.className='ghost editDeadlineDateBtn';b.type='button';b.textContent='Data';b.onclick=()=>openDeadlineEdit(id);if(pay)actions.insertBefore(b,pay);else actions.insertBefore(b,del||null)})}
const css=document.createElement('style');css.textContent=`.fieldLabel{display:grid;gap:6px;font-size:11px;color:#7b879b;font-weight:800}.fieldLabel input{font-weight:700}.editDeadlineDateBtn{background:#eef3f8!important;color:#26364f!important}`;document.head.appendChild(css);
injectDeadlineEditor();enhanceDeadlineRows();const oldRender=window.render;if(oldRender&&!oldRender.__dd){let nr=function(){oldRender();enhanceDeadlineRows()};nr.__dd=true;window.render=nr}
})();