(()=>{function toast(msg,type='ok'){let old=document.getElementById('appToast');if(old)old.remove();let el=document.createElement('div');el.id='appToast';el.className='appToast '+type;el.innerHTML=`<span>${type==='ok'?'✓':'✦'}</span><b>${msg}</b>`;document.body.appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),250)},2200)}
function haptic(){try{navigator.vibrate&&navigator.vibrate(18)}catch(e){}}
function monthDelta(){let now=monthNow(),dt=new Date(now+'-01T12:00:00');dt.setMonth(dt.getMonth()-1);let prev=`${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}`,a=monthTotal(now),b=monthTotal(prev);if(!b)return null;return{amount:a-b,pct:(a-b)/b*100}}
function contextualInsight(){let c=currentCalc(),delta=monthDelta(),tot=categoryTotals(c.m),top=Object.entries(tot).sort((a,b)=>b[1]-a[1])[0],parts=[];if(delta){let dir=delta.amount<=0?'meno':'più';parts.push(`Hai speso <b>${eur(Math.abs(delta.amount))} ${dir}</b> rispetto al mese scorso.`)}if(top&&top[1]>0)parts.push(`La categoria principale è <b>${esc(top[0])}</b> con ${eur(top[1])}.`);let real=(d.goalContributions||[]).filter(x=>x.month===c.m).reduce((s,x)=>s+Number(x.amount||0),0);if(real>0)parts.push(`Hai già accantonato <b>${eur(real)}</b> questo mese.`);return parts.join(' ')}
function injectInsight(){let a=document.getElementById('assistantCard');if(!a||document.getElementById('contextInsight'))return;let x=document.createElement('div');x.id='contextInsight';x.className='contextInsight';a.appendChild(x)}
function renderInsight(){let x=document.getElementById('contextInsight');if(x)x.innerHTML='<span>✦</span><div><small>IN BREVE</small><p>'+contextualInsight()+'</p></div>'}
function wrapExpense(){let original=window.addExpense;if(!original||original.__ux)return;let fn=function(){let a=Number(exAmt.value),cat=exCat.value;if(!(a>0))return original();original();haptic();toast(`${eur(a)} registrati · ${cat}`)};fn.__ux=true;window.addExpense=fn}
function wrapSaving(){let original=window.addSaving;if(!original||original.__ux)return;let fn=function(i){let before=d.goals[i]?.saved||0,name=d.goals[i]?.name||'Obiettivo';original(i);let after=d.goals.find(x=>x.name===name)?.saved??before;if(after>before){haptic();toast(`+${eur(after-before)} su ${name}`)}};fn.__ux=true;window.addSaving=fn}
function wrapDeadline(){let original=window.payDeadline;if(!original||original.__ux)return;let fn=function(id){let x=d.deadlines.find(v=>v.id===id),before=x?.next;original(id);if(x&&x.next!==before){haptic();toast(`${x.name} pagata e registrata`)}};fn.__ux=true;window.payDeadline=fn}
function enhanceSheet(){let s=document.querySelector('.sheet');if(!s||s.dataset.ux)return;s.dataset.ux=1;let amt=document.getElementById('exAmt');if(amt){amt.inputMode='decimal';amt.placeholder='0,00';let h=s.querySelector('h2');if(h)h.innerHTML='<span class="sheetEyebrow">NUOVA SPESA</span><span>Quanto hai speso?</span>'}let save=[...s.querySelectorAll('button')].find(b=>(b.textContent||'').toLowerCase().includes('salva')||(b.textContent||'').toLowerCase().includes('registra'));if(save){save.id='smartSaveExpense';let update=()=>{let v=Number(amt?.value||0);save.textContent=v>0?`Registra ${eur(v)}`:'Registra spesa'};amt?.addEventListener('input',update);update()}}
function animateBars(){document.querySelectorAll('.bar i').forEach(x=>{let w=x.style.width;x.style.width='0';requestAnimationFrame(()=>requestAnimationFrame(()=>x.style.width=w))})}
const css=document.createElement('style');css.textContent=`.appToast{position:fixed;left:50%;bottom:88px;transform:translate(-50%,18px);opacity:0;z-index:50;background:#0b1830;color:#fff;border-radius:16px;padding:11px 15px;display:flex;align-items:center;gap:9px;box-shadow:0 14px 35px #0f172a40;transition:.22s ease;max-width:calc(100vw - 32px);white-space:nowrap;font-size:12px}.appToast span{width:23px;height:23px;border-radius:50%;display:grid;place-items:center;background:#ffffff18}.appToast.show{opacity:1;transform:translate(-50%,0)}.contextInsight{margin-top:12px;padding-top:13px;border-top:1px solid #e6eaf0;display:flex;gap:10px;align-items:flex-start}.contextInsight>span{width:30px;height:30px;flex:0 0 30px;border-radius:10px;background:#eef2ff;color:#4f46e5;display:grid;place-items:center}.contextInsight small{font-size:9px;font-weight:900;letter-spacing:.1em;color:#8a94a6}.contextInsight p{font-size:12px;line-height:1.45;margin:3px 0 0;color:#536074}.sheetEyebrow{display:block;font-size:9px;letter-spacing:.12em;color:#8b96a8;margin-bottom:5px}.sheet h2>span:last-child{display:block}.sheet #exAmt{font-size:30px;font-weight:850;letter-spacing:-1px;padding:15px 14px;text-align:left}.bar i{transition:width .55s cubic-bezier(.2,.8,.2,1)}#smartSaveExpense{font-size:14px;box-shadow:0 8px 20px #0d1b3525}@media(prefers-reduced-motion:reduce){.bar i,.appToast{transition:none}}`;document.head.appendChild(css);
injectInsight();enhanceSheet();wrapExpense();wrapSaving();wrapDeadline();const oldRender=window.render;if(oldRender&&!oldRender.__micro){let nr=function(){oldRender();injectInsight();renderInsight();enhanceSheet();wrapExpense();wrapSaving();wrapDeadline();animateBars()};nr.__micro=true;window.render=nr}renderInsight();setTimeout(animateBars,80);
})();