(()=>{
function dayInfo(){const n=new Date(),days=new Date(n.getFullYear(),n.getMonth()+1,0).getDate(),day=n.getDate();return{day,days,progress:Math.max(.05,day/days),left:Math.max(0,days-day)}}
function discretionarySpent(){let names=new Set((d.cats||[]).map(x=>x[0]));return monthExpenses(monthNow()).filter(x=>names.has(x.cat)).reduce((s,x)=>s+Number(x.amount||0),0)}
function projectedDiscretionary(){let t=dayInfo(),spent=discretionarySpent();return Math.min(spent/t.progress,spent+Math.max(0,d.life-spent)*2)}
function projectedStatus(){let projected=projectedDiscretionary(),diff=d.life-projected;if(projected<=d.life*.9)return{label:'OTTIMO',cls:'good',text:`Al ritmo attuale dovresti chiudere il mese circa a <b>${eur(projected)}</b>, sotto il budget vita di ${eur(d.life)}.`};if(projected<=d.life)return{label:'IN LINEA',cls:'good',text:`Al ritmo attuale dovresti chiudere il mese circa a <b>${eur(projected)}</b>, ancora dentro il budget vita.`};if(projected<=d.life*1.15)return{label:'ATTENZIONE',cls:'warn',text:`Al ritmo attuale potresti chiudere circa a <b>${eur(projected)}</b>, circa ${eur(Math.abs(diff))} sopra il budget vita.`};return{label:'DA CORREGGERE',cls:'bad',text:`Il ritmo attuale porta verso circa <b>${eur(projected)}</b>, cioè ${eur(Math.abs(diff))} oltre il budget vita. Conviene rallentare le categorie discrezionali.`}}
function safestCategory(){if(typeof smartBudgets!=='function')return null;let rows=smartBudgets().filter(x=>x.left>0).sort((a,b)=>b.left-a.left);return rows[0]||null}
function monthlySavingForecast(){let p=projectedDiscretionary(),base=Math.max(0,d.salary-fixedMonthly()-essentialTotal()-p)+Number(d.extra||0);return base}
function injectPrediction(){let a=document.getElementById('assistantCard');if(!a||document.getElementById('predictiveBlock'))return;let box=document.createElement('div');box.id='predictiveBlock';box.className='predictiveBlock';box.innerHTML=`<div class="predictionHead"><div><small>PREVISIONE</small><strong>Fine mese</strong></div><span id="predictionBadge" class="pill">—</span></div><div id="predictionCopy" class="predictionCopy"></div><div class="predictionGrid"><div><span>Spesa discrezionale prevista</span><b id="predictedSpend">€0</b></div><div><span>Risparmio potenziale</span><b id="predictedSaving">€0</b></div></div><div id="safeSpendTip" class="safeSpendTip"></div>`;a.appendChild(box)}
function renderPrediction(){injectPrediction();let st=projectedStatus(),badge=document.getElementById('predictionBadge');if(!badge)return;badge.textContent=st.label;badge.className=`pill ${st.cls}`;predictionCopy.innerHTML=st.text;predictedSpend.textContent=eur(projectedDiscretionary());predictedSaving.textContent=eur(monthlySavingForecast());let best=safestCategory(),lifeLeft=Math.max(0,d.life-discretionarySpent());if(best){let safe=Math.max(0,Math.min(best.left,lifeLeft));safeSpendTip.innerHTML=`<span>✦</span><div><small>SPESA SICURA</small><p>In <b>${esc(best.name)}</b> puoi spendere ancora circa <b>${eur(safe)}</b> restando nel piano attuale.</p></div>`}else safeSpendTip.innerHTML=`<span>✦</span><div><small>SPESA SICURA</small><p>Non vedo margine discrezionale libero nelle categorie attuali.</p></div>`}
const css=document.createElement('style');css.textContent=`.predictiveBlock{margin-top:14px;padding-top:14px;border-top:1px solid #e5eaf1}.predictionHead{display:flex;align-items:center;justify-content:space-between;gap:10px}.predictionHead small{display:block;font-size:9px;letter-spacing:.12em;font-weight:900;color:#8b96a8}.predictionHead strong{display:block;font-size:16px;margin-top:2px}.predictionCopy{font-size:12.5px;line-height:1.48;color:#59677b;margin:9px 0 11px}.predictionGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.predictionGrid>div{background:#fff;border:1px solid #e7ebf1;border-radius:14px;padding:11px}.predictionGrid span{display:block;font-size:10px;color:#8792a4;font-weight:750;line-height:1.25}.predictionGrid b{display:block;font-size:17px;margin-top:4px}.safeSpendTip{display:flex;gap:9px;align-items:flex-start;background:#eef5ff;border:1px solid #dce9fb;border-radius:14px;padding:11px;margin-top:9px}.safeSpendTip>span{width:27px;height:27px;flex:0 0 27px;border-radius:9px;background:#fff;display:grid;place-items:center;color:#2563eb}.safeSpendTip small{font-size:9px;letter-spacing:.1em;font-weight:900;color:#6d7b91}.safeSpendTip p{font-size:12px;line-height:1.4;margin:2px 0 0;color:#45546a}`;document.head.appendChild(css);
injectPrediction();renderPrediction();const oldRender=window.render;if(oldRender&&!oldRender.__predictive){let nr=function(){oldRender();renderPrediction()};nr.__predictive=true;window.render=nr}
})();